# Source: https://github.com/qoomon/actions/blob/main/workflows/dependabot-auto-merge.yaml

# Repository Setup
# - Settings > General > Check "Allow auto-merge Loading"
#   => https://github.com/OWNER/REPO/settings
# - Settings > Actions > General > Check "Allow GitHub Actions to create and approve pull requests"
#   => https://github.com/OWNER/REPO/settings/actions

name: Dependabot auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: metadata
      
      # possible update-type values :version-update:semver-major, version-update:semver-minor, and version-update:semver-patch
      - if: >-
          steps.metadata.outputs.update-type == 'version-update:semver-minor' || 
          steps.metadata.outputs.update-type == 'version-update:semver-patch'
        name: Auto-merge changes from Dependabot
        uses: actions/github-script@v7
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '@dependabot squash and merge',
              })
